version: '2.3'

# if 'docker-compose run' is used
# do not forget '--service-ports'!

services:
    audio-classification-tf:
      image: deephdc/deep-oc-audio-classification-tf
      ports:
        - 5000:5000
        - 6006:6006
      entrypoint: ["deepaas-run", "--listen-ip=0.0.0.0"]


    audio-classification-tf-gpu:
      image: deephdc/deep-oc-audio-classification-tf:gpu
      runtime: nvidia
      ports:
        - 5000:5000
        - 6006:6006
      entrypoint: ["deepaas-run", "--listen-ip=0.0.0.0"]


    audio-classification-tf-rclone:
      extends:
        service: audio-classification-tf
      volumes:
        - $HOME/.config/rclone:/srv/.rclone
      environment:
        - RCLONE_CONFIG=/srv/.rclone/rclone.conf
