# .sqa/config.yml - jenkins-pipeline-library configuration file
sqa_criteria:
  qc_style:
    repos:
      audio_vessel_classifier:
        container: thisrepo-testing
        tox:
          tox_file: tox.ini
          testenv:
            - qc.sty
  qc_coverage:
    repos:
      audio_vessel_classifier:
        container: thisrepo-testing
        tox:
          tox_file: tox.ini
          testenv:
            - qc.cov
  qc_security:
    repos:
      audio_vessel_classifier:
        container: thisrepo-testing
        tox:
          tox_file: tox.ini
          testenv:
            - qc.sec

environment:
  LANG: C.UTF-8

timeout: 600